// Copyright 2017-2024 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/apps-config

import type { OverrideBundleType } from '@polkadot/types/types';

/* eslint-disable quotes */
/* eslint-disable quote-props */
/* eslint-disable sort-keys */

export const typesBundle = {
  "spec": {
    "cord": {
      "runtime": {
        "DidApi": [
          {
            "methods": {
              "query_by_name": {
                "description":
                  "Return the information relative to the owner of the provided didName, if any.",
                "params": [
                  {
                    "name": "name",
                    "type": "Text"
                  }
                ],
                "type": "Option<RawDidLinkedInfo>"
              },
              "query": {
                "description":
                  "Return the information relative to the owner of the provided DID, if present.",
                "params": [
                  {
                    "name": "did",
                    "type": "AccountId32"
                  }
                ],
                "type": "Option<RawDidLinkedInfo>"
              }
            },
            "version": 1
          }
        ],
        "TransactionWeightApi": [
          {
            "methods": {
              "query_weight_info": {
                "description": "The transaction weight info",
                "params": [
                  {
                    "name": "uxt",
                    "type": "Extrinsic"
                  }
                ],
                "type": "RuntimeDispatchInfo"
              }
            },
            "version": 1
          }
        ]
      },
      "types": [
        {
          "minmax": [
            0,
            null
          ],
          "RawDidLinkedInfo": {
            "identifier": "AccountId32",
            "account": "AccountId32",
            "name": "Option<Text>",
            "serviceEndpoints": "Vec<PalletDidServiceEndpointsDidEndpoint>",
            "details": "PalletDidDidDetails"
          },
          "RuntimeDispatchWeightInfo": {
            "weight": "Weight",
            "class": "DispatchClass"
          },
          "RuntimeDispatchWeightInfoV1": {
            "weight": "WeightV1",
            "class": "DispatchClass"
          },
          "RuntimeDispatchWeightInfoV2": {
            "weight": "WeightV2",
            "class": "DispatchClass"
          }
        }
      ]
    }
  }
} as unknown as OverrideBundleType;
